rest-integration
ulxanxv/monetarys pull request #4
Opened 2020-11-26 14:54 UTC by ulxanxv

Fixed all issues

2020-11-27 08:49 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileServiceImpl.java
> +                UriComponentsBuilder.newInstance().scheme("http").host(apiProperties.getHost()).path(apiProperties.getClientInfoByGuidPath()).build().toUriString(),
Добавь тут: `.queryParam("clientGUID", guid)`
И желательно вынести отдельной строчкой. Вот так будет:
```
URI uri = UriComponentsBuilder.fromHttpUrl(appProperties.getClientProfileService().getUrl())
    .path(apiProperties.getClientInfoByGuidPath())
    .queryParam("clientGUID", guid)
    .build()
    .toUri();
```

2020-11-27 08:50 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileServiceImpl.java
> +                Collections.singletonMap("guid", guid)
Это удалить

2020-11-27 08:51 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileServiceImpl.java
> +           return null;
Тут скорей всего тоже исключение стоит выбрасывать. Давай хотя-бы ClientProfileNotFound кинем

2020-11-27 08:54 UTC, VasilisaLapygina commented on src/main/resources/application-dev.yaml
> +  client-info-by-guid-path: /v1/clientInfoByGUID/{guid}
{guid} - это не нужно. Посмотри еще раз swagger

2020-11-27 08:59 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/exceptions/ClientProfileNotFound.java
> +public class ClientProfileNotFound extends RuntimeException {
Сделай тут так же атрибуты message и guid. Тебе они пригодятся что бы вернуть в ответе пользователю в случае ошибки.

2020-11-27 09:01 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/exceptions/AccountNotFound.java
> +public class AccountNotFound extends RuntimeException {
Сделай тут так же атрибуты message и guid. Тебе они пригодятся что бы вернуть в ответе пользователю в случае ошибки.

2020-11-27 09:02 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/exceptions/ClientProfileNotFound.java
> +public class ClientProfileNotFound extends RuntimeException {
И почему эти 2 исключения не объединить? Будет разный код, а исключение одно можно сделать

2020-11-27 09:15 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileApiProperties.java
> +public class ClientProfileApiProperties {
Смысл такой, все правильно. Только давай сделаем: @ConfigurationProperties(prefix = "application"). Целый класс для трех полей создавать грустно, а так мы этот класс еще много раз по используем.

А уже внутри объект ClientProfile

```
private ClientProfile clientProfile; // или лучше сlientProfileService но тогда и в файле конфигурации обнови

@Data
public static class ClientProfile {
      private String host;
      private String clientInfoByGuidPath;
      private String secret;
}
```

2020-11-27 09:16 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileApiProperties.java
> +@Getter
Вместо `@Getter` и `@Setter` лучше `@Data`

2020-11-27 09:19 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileServiceImpl.java
> +        restTemplate.getInterceptors().add(new HeaderRequestInterceptor("Authorization", "Basic " + apiProperties.getSecret()));
Не надо при каждом вызове метода ставить Interceptor. Один раз устанавливай в конфигурации RestTemplate

2020-11-27 09:20 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileServiceImpl.java
> +        restTemplate.getInterceptors().add(new HeaderRequestInterceptor("Authorization", "Basic " + apiProperties.getSecret()));
И по требованиям не "Basic". А в заголовке "Authorization" ключ. 

"Basic" просто удалить

2020-11-27 09:25 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/config/ServiceProperties.java
> +public class ServiceProperties {
ServiceProperties это имелся в виду из ConfigurationProperties конфигурация сервиса clientProfile. Это так же должно быть вынесено в файл конфигурации

2020-11-27 10:15 UTC, m-obrubov commented on pom.xml
> +			<version>2.4.0</version>
Версию брать из родительского проекта

2020-11-27 10:17 UTC, m-obrubov commented on pom.xml
> +			<version>2.9.2</version>
Версии лучше выносить в блок properties, а в зависимости ссылаться на них. Так все версии находятся в одном месте и ими легче управлять.
```
<properties>
    <springfox.version>2.9.2</springfox.version>
</properties>
...
<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger2</artifactId>
    <version>${springfox.version}</version>
</dependency>
```

2020-11-27 10:18 UTC, m-obrubov commented on pom.xml
>              <artifactId>spring-boot-test</artifactId>
Он должен входить в `spring-boot-starter-test`

2020-11-27 10:55 UTC, m-obrubov requested changes

2020-11-27 10:55 UTC, m-obrubov commented on src/main/java/ru/monetarys/config/RestClientConfiguration.java
> +    public HttpClient httpClient(ServiceProperties properties) {
Думаю, что отдельными бинами эти объекты делать не стоит, лучше сделать приватными методами, потому что: 

1. этот бин будет использоваться только в соседнем методе этой конфигурации 
2. В проекте может быть несколько RestTemplate и создавать для каждого свои конфигурационные бины - не очень хорошо

Естественно, это только про этот конкретный случай. В другом случае всё может быть совсем по другому

2020-11-27 10:55 UTC, m-obrubov commented on src/main/java/ru/monetarys/config/RestClientConfiguration.java
> +    public ClientHttpRequestFactory clientHttpRequestFactory(HttpClient httpClient) {
см. коммент выше

2020-11-27 10:55 UTC, m-obrubov commented on src/main/java/ru/monetarys/dto/ClientAccountInfo.java
> +    private String cur;
Лучше обзывать параметры адекватными именами, даже если они в интеграции названы не очень. Тут явно, что придет валюта - `currency`

2020-11-27 10:55 UTC, m-obrubov commented on src/main/java/ru/monetarys/dto/ClientAccountInfo.java
> +    @JsonProperty(value = "bankName", required = true)
Если `value` совпадает с названием поля, то это `value` писать смысла нет - только загромождает код

2020-11-27 10:55 UTC, m-obrubov commented on src/main/java/ru/monetarys/dto/ClientGeneralInfo.java
> +
Куча странных пробелов :)

2020-11-27 10:55 UTC, m-obrubov commented on src/main/java/ru/monetarys/exceptions/AccountNotFound.java
> +    public enum ErrorCode {
Это лучше вынести в отдельный файл, так как скорее всего будет использоваться в разных местах проекта

2020-11-27 10:55 UTC, m-obrubov commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileServiceImpl.java
> +        if ((Objects.requireNonNull(clientInfo).getAccountList() == null) || (clientInfo.getAccountList().size() == 0)) {
`Objects.requireNonNull` тут не нужен, так как выше это проверяется. Да и вообще использовать это надо с осторожностью, так как он просто выкидывает NPE

2020-11-27 11:00 UTC, m-obrubov commented on src/main/java/ru/monetarys/security/UserDetailsServiceImpl.java
> +        if (optionalCredential.isEmpty()) {
Более короткая конструкция:
`Credential credential = credentialRepository.findByName(s).orElseThrow(() -> new SomeException());`

2020-11-30 09:23 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileProperties.java
> +    private ClientProfileService    clientProfileService;
Пробелы лишние

2020-11-30 10:23 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileProperties.java
> +    public static class ServiceProperties {
Как правило эти настройки устанавливаются для каждой интеграции свои. Лучше вынести в ClientProfileService.

2020-11-30 10:23 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileServiceImpl.java
> +                restTemplate.getForEntity(uri.toString(), ClientGeneralInfo.class);
".toString()" обязательно? Если я не ошибаюсь URI тоже принимает getForEntity

2020-11-30 10:23 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileServiceImpl.java
> +            throw new ClientException(ErrorCode.PROFILE_NOT_FOUND, "Не найден профиль клиента", guid);
Сообщения по типу "Не найден профиль клиента" и "Не найден ни один счёт клиента" лучше вынести в конфиги они меняются часто

А в исключении будет достаточно ErrorCode

2020-11-30 10:23 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileServiceImpl.java
> +        if ((response.getStatusCode() != HttpStatus.OK) || (clientInfo = response.getBody()) == null) {
Это плохо читается (clientInfo = response.getBody()) == null), лучше вынести выше ClientGeneralInfo clientInfo = response.getBody()

2020-11-30 12:25 UTC, m-obrubov commented on src/main/java/ru/monetarys/config/RestClientConfiguration.java
> +        restTemplate
Всё же RestTemplate'ы удобнее конфигурировать через RestTemplateBuilder, когда конфигурации становится слишком много. Погугли на досуге

2020-11-30 12:27 UTC, m-obrubov commented on src/main/java/ru/monetarys/config/RestClientConfiguration.java
> +                .add(new HeaderRequestInterceptor(apiProperties.getClientProfileService().getAuthHeaderName(), apiProperties.getClientProfileService().getSecret()));
`apiProperties.getClientProfileService().getAuthHeaderName()` можно зашить в коде в виде `HttpHeaders.AUTHORIZATION`

2020-11-30 12:31 UTC, m-obrubov commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileProperties.java
> +public class ClientProfileProperties {
Раз уж у нас этот класс теперь содержит все настройки, то логичнее назвать его ApplicationProperties

2020-11-30 12:33 UTC, m-obrubov commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileProperties.java
> +    public static class ServiceProperties {
А ещё лучше заняться переиспользованием и вынести общие настройки в общий родительский класс

2020-12-01 13:40 UTC, VasilisaLapygina approved these changes

2020-12-01 13:40 UTC, m-obrubov approved these changes

2020-12-01 13:45 UTC, merged