integration-test
ulxanxv/monetarys pull request #7
Opened 2020-12-08 15:23 UTC by ulxanxv

2020-12-09 09:42 UTC, VasilisaLapygina requested changes

2020-12-09 09:42 UTC, VasilisaLapygina commented on src/test/java/ru/monetarys/rest/RestIntegrationTests.java
> +@SpringBootTest
`@SpringBootTest` не стоит писать в unit тестах

Если ты будешь тянуть Spring во всех unit тестах прогоняться они будут мучительно долго

2020-12-09 09:42 UTC, VasilisaLapygina commented on src/test/java/ru/monetarys/rest/RestIntegrationTests.java
> +class RestIntegrationTests {
Лучше именовать по наименованию класса который тестируешь + постфикс Test

2020-12-09 09:42 UTC, VasilisaLapygina commented on src/test/java/ru/monetarys/rest/RestIntegrationTests.java
> +@ActiveProfiles("test")
Тоже не нужно

2020-12-09 09:42 UTC, VasilisaLapygina commented on src/test/java/ru/monetarys/rest/RestIntegrationTests.java
> +    private ApplicationProperties properties;
Аннотацию `@Autowired` стоит убрать и создать тестовый объект в ручную

2020-12-09 09:42 UTC, VasilisaLapygina commented on src/test/java/ru/monetarys/rest/RestIntegrationTests.java
> +        String guid = UUID.randomUUID().toString();
Лучше внести в отдельный класс с константами. И рандом не использовать.

Так легче будет в дальнейшем писать тесты, константы можно будет переиспользовать и изменять тесты потом тоже будет удобнее

2020-12-09 09:42 UTC, VasilisaLapygina commented on src/test/java/ru/monetarys/rest/RestIntegrationTests.java
> +        ClientGeneralInfo client = new ClientGeneralInfo();
Создание тестовых объектов тоже стоит вынести в отдельные класс. Желательно для каждого тестируемого класса создавать свой утилитный тестовый класс.

Желательно еще его пометить: `@UtilityClass`

2020-12-09 09:42 UTC, VasilisaLapygina commented on src/test/java/ru/monetarys/rest/RestIntegrationTests.java
> +        Mockito
Очень странное форматирование, слишком много места занимает

2020-12-10 11:58 UTC, m-obrubov requested changes

2020-12-10 11:58 UTC, m-obrubov commented on src/test/java/ru/monetarys/rest/ClientProfileServiceImplTest.java
> +                () -> service.getClientInfoByGUID("123")
Во всех таких местах замени тоже на константу `GUID`

2020-12-10 11:58 UTC, m-obrubov commented on src/test/java/ru/monetarys/rest/ClientProfileServiceImplTest.java
> +    public void successfulClientSearchWithSomeData() {
Тут хорошо бы ещё проверить, что возвращается полная структура ответа, которая тебе нужна. У нас же ещё поля по клиенту были кроме GUID и списка счетов

2020-12-10 12:01 UTC, m-obrubov commented on src/test/java/ru/monetarys/rest/ClientProfileServiceImplTest.java
> +        Mockito.when(restTemplate.getForEntity(any(), any()))
В тесте, в части с проверками также нужно проверить, что были вызваны все необходимые зависимости. В нашем случае это только `RestTemplate`. В классе `Mockito` есть метод `verify`, при помощи которого можно это сделать.

2020-12-11 12:26 UTC, m-obrubov requested changes
На `TransferReceiver` тоже нужно написать тесты

2020-12-11 12:26 UTC, m-obrubov commented on src/test/java/ru/monetarys/rest/ClientProfileServiceImplTest.java
> +        Mockito.verify(restTemplate, Mockito.times(1)).getForEntity(any(), any());
Тут хорошо бы ещё проверять как произошел вызов - какой URL, какие параметры

2020-12-11 12:26 UTC, m-obrubov commented on src/test/java/ru/monetarys/rabbit/TransferSenderTest.java
> +        verify(rabbitTemplate, times(1)).convertAndSend(anyString(), anyString(), any(TransferRequest.class));
Тоже хорошо бы проверить параметры

2020-12-14 07:38 UTC, m-obrubov approved these changes

2020-12-14 07:59 UTC, merged