Merge branch 'master' into business-logic
ulxanxv/monetarys pull request #8
Opened 2020-12-15 21:22 UTC by ulxanxv

added business logic

2020-12-16 17:10 UTC, VasilisaLapygina requested changes

2020-12-16 17:10 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/transfer/TransferComponent.java
> +                        x -> (x < 16 || x > 22),
Может не нужны эти скобки? Как-то топорно смотрится на мой взгляд

2020-12-16 17:10 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/transfer/TransferUtil.java
> +
Осторожнее, много лишних пробелов ставишь

2020-12-16 17:10 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/transfer/TransferControllerAdvice.java
> +    public ResponseEntity<?> handleTransferValidateException(TransferValidateException exception) {
В ответ надо вернуть Атрибут/переменная, Код ошибки, Текст ошибки
Давай обозначим вот такую структуру ошибки: 
```
{
  "errorCode": "validation.Error"
  "attrErrors": [
    {
      "attrName": "string",
      "code": "string",
      "message": "string"
    }
  ]
}
```

2020-12-16 17:10 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/transfer/TransferControllerAdvice.java
> +public class TransferControllerAdvice {
Лучше еще их логировать тут.

2020-12-16 17:10 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/transfer/TransferController.java
> +@RestController(value = "/")
Давай v1 сюда вынесем

2020-12-16 17:10 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/transfer/TransferComponent.java
> +    private ClientProfileServiceImpl clientProfileService;
Лучше через конструктоp

2020-12-16 17:10 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/services/clientprofile/ClientProfileServiceImpl.java
>          if ((response.getStatusCode() != HttpStatus.OK) || (clientInfo) == null) {
А зачем скобочки вокруг clientInfo? Давай уберем

2020-12-16 17:10 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/transfer/TransferComponent.java
> +                        TransferErrorCode.PAYER_ACCOUNT_NOT_VALID)
Везде последнюю скобку хорошо бы убирать к `).validate(` или переносить, но так много места занимает

2020-12-22 08:45 UTC, m-obrubov requested changes

2020-12-22 08:45 UTC, m-obrubov commented on pom.xml
> +			<version>1.4.1.Final</version>
Версию хорошо бы вынести в раздел `properties`

2020-12-22 08:45 UTC, m-obrubov commented on pom.xml
> +						</path>
По версиям аналогично

2020-12-22 08:45 UTC, m-obrubov commented on src/main/java/ru/monetarys/integration/ApplicationProperties.java
> +        private String[] availableAccountCurrencies;
Лучше использовать коллекции, так как сразу есть много полезных методов, например `contains`

2020-12-22 08:45 UTC, m-obrubov commented on src/main/java/ru/monetarys/web/TransferControllerAdvice.java
> +    public ResponseEntity<?> handleTransferValidateException(TransferValidateException exception) {
Можно возвращать конкретный тип и указывать статус ответа аннотацией `@ResponseStatus`, без `ResponseEntity`

2020-12-22 08:45 UTC, m-obrubov commented on src/main/java/ru/monetarys/web/TransferControllerAdvice.java
> +        log.error(exception.toString());
Логировать лучше исключение целиком, иначе как потом разберешь ошибку.
Например, так: `log.error("Error '{}' occured, exception.getMessage(), exception);`

2020-12-22 08:45 UTC, m-obrubov commented on src/main/java/ru/monetarys/web/TransferUtil.java
> +    public Transfer getTransfer(ApplicationProperties applicationProperties, TransferRequest transferRequest, ClientGeneralInfo payer, ClientGeneralInfo payee, ClientAccountInfo payeeAccount) {
При форматировании кода желательно придерживаться определенной максимальной длины строки. В IDEA есть для этого вертикальная полоска, шириной в 120 символов

2020-12-22 08:45 UTC, m-obrubov commented on src/main/java/ru/monetarys/web/TransferUtil.java
> +@UtilityClass
Желательно избегать статических классов и статических методов, потому что ими сложно управлять, их сложно тестировать

2020-12-22 08:45 UTC, m-obrubov commented on src/main/java/ru/monetarys/web/controller/TransferController.java
> +    @Autowired
Лучше везде пользоваться инъекцией зависимостей через конструктор

2020-12-22 08:45 UTC, m-obrubov commented on src/main/java/ru/monetarys/web/helper/TransferValidateHelper.java
> +    {
Инициализаторы лучше не применять. Очень путают. Используй конструктор или в строке объявления поля.

2020-12-22 08:45 UTC, m-obrubov commented on src/main/java/ru/monetarys/web/helper/TransferValidateHelper.java
> +                exception = exceptionClass.getDeclaredConstructor().newInstance();
Для этого есть удобный класс `ReflectionUtils`

2020-12-22 08:45 UTC, m-obrubov commented on src/main/java/ru/monetarys/web/ro/TransferResponseRo.java
> +    private TransactionResponseRo transaction;
Все эти классы можно сделать внутренними. Так всё будет в одном месте, не будет лишних мелких классов и не надо будет составлять длинные названия. Для запроса то же самое

2020-12-22 08:45 UTC, m-obrubov commented on src/main/java/ru/monetarys/web/service/TransferServiceImpl.java
> +                        x -> x.compareTo(new BigDecimal("0.0")) < 0,
Есть константа `BigDecimal.ZERO`

2020-12-22 08:45 UTC, m-obrubov commented on src/test/java/ru/monetarys/rest/ClientProfileServiceImplTest.java
> +    {
Инициализаторы == не хорошо

2020-12-22 08:45 UTC, m-obrubov commented on src/main/java/ru/monetarys/logic/impl/TransferManager.java
> +    TransferResponseRo transferMoney(TransferRequest transferRequest);
Слой менеджеров должен взаимодействовать только с доменными объектами. Маппинг Domain <-> Ro должен выполняться в сервисах.

2020-12-22 08:45 UTC, m-obrubov commented on src/main/java/ru/monetarys/logic/impl/TransferManager.java
> +    void validatePayee(ClientGeneralInfo payee, ClientGeneralInfo payer, ClientAccountInfo payeeAccount, ClientAccountInfo payerAccount);
Зачем эти методы вынесены в интерфейс? Они ведь нужны только самому менеджеру

2020-12-22 08:55 UTC, m-obrubov commented
И ещё примерные рекомендации по расположению в пакетах:
![image](https://user-images.githubusercontent.com/31563836/102869372-93095e00-444c-11eb-9409-951fcb163b63.png)

2020-12-22 10:02 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/exceptions/ro/ErrorDefinitionRo.java
> +    @JsonProperty(value = "attributeName")
Наверное наоборот хотел? Поле обозвать attributeName а в json attrName

2020-12-22 10:02 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/logic/manager/TransferManagerImpl.java
> +                    x -> x.getFirstName().isEmpty() || x.getLastName().isEmpty(),
NPE. Лучше использовать StringUtils.isEmpty.

2020-12-22 10:02 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/logic/manager/TransferManagerImpl.java
> +                    applicationProperties.getTransferMoney().getAvailablePayerAccountStatuses(),
Странно, лучше сразу сделай коллекций

2020-12-22 10:02 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/logic/manager/TransferManagerImpl.java
> +        ClientGeneralInfo payer         = clientProfileService.getClientInfoByGuid(transferRequest.getPayer().getGuid());
Почему-то не нравиться такое форматирование, первый раз вижу что-бы так писали. Ты где такому научился?

2020-12-22 10:02 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/web/service/TransferServiceImpl.java
> +                        x -> Pattern.matches("40111\\d{15}", x) || Pattern.matches("40222\\d{15}", x) || Pattern.matches("40333\\d{15}", x),
Справочник предполагает вынесение в отдельное место,  лучше в конфиги

2020-12-22 10:02 UTC, VasilisaLapygina commented on src/main/java/ru/monetarys/web/service/TransferServiceImpl.java
> +                        x -> x < 16 || x > 22,
Можно проверить matches("^\\d{16,22}$") но не обязательно

2020-12-22 13:16 UTC, ulxanxv commented on src/main/java/ru/monetarys/logic/manager/TransferManagerImpl.java
> +        ClientGeneralInfo payer         = clientProfileService.getClientInfoByGuid(transferRequest.getPayer().getGuid());
Хех, на самом деле у The Witcher 3 был открытый исходный код и я увидел, что они так форматируют свой код) Мне понравилось почему-то, но могу так не писать

2020-12-22 17:43 UTC, ulxanxv commented on src/main/java/ru/monetarys/exceptions/ro/ErrorDefinitionRo.java
> +    @JsonProperty(value = "attributeName")
Ой, да, перепутал)

2020-12-29 11:52 UTC, m-obrubov approved these changes

2020-12-29 11:52 UTC, VasilisaLapygina approved these changes

2020-12-29 13:01 UTC, merged